### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by tbarto** [tbarto/CommunicationStation#1]
To Do:
=======
- [ ] Refactor three buttons
- [ ] Add firebase database
- [ ] Login/authentication
- [ ] Error handling
- [ ] Add sections, stores
